spring:
  datasource:
    url: jdbc:mysql://172.16.10.225:3306/db_template_project?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: operator
    password: s3culus
    testWhileIdle: true
    validationQuery: SELECT 1
    continue-on-error: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    title: Template
